name: run main2 test
on:
  schedule: # Times are in UTC
  - cron: '0 1,2,4 * * *' # Every night at 9pm and 11pm
  - cron: '0 2,19,20,21,22,23 * * 6' # 9pm on Friday + Afternoon hourly on Saturday starting at 2pm
  - cron: '0 0,1,2,3,15,17,19,21,23 * * 0' # Continuation of hourly Saturday until 10pm + Sunday every 2 hours starting at 10am
  - cron: '0 1,3,14,17,20,23 * * 1' # Continuation of Sunday runs until 10pm + Monday 9am, 12pm, 3pm, 6pm

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'site rebuild'
        env:
          GSPREAD_CREDENTIALS: ${{ secrets.GSPREAD_CREDENTIALS }}
        run: |
          python rebuild.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'GITHUB-ACTIONS: Pulled in data and rebuilt site'
          git push
